api:
  version: Alpha

spring:
  application:
    name: inwent
  boot:
    admin:
      client:
        url: ${ADMIN_URL:http://localhost:8090}
  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/inwent
    username: ${POSTGRES_USER:inwent}
    password: ${POSTGRES_PASS:inwent-pass}
#    initialization-mode: always

springdoc:
  swagger-ui:
    url: "/v3/api-docs"
  default-produces-media-type: "application/json"


management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

#look out! following line fucks up all the other log configs!
#debug=true

logging:
  level:
    io.r2dbc.postgresql.QUERY: DEBUG # for queries
    io.r2dbc.postgresql.PARAM: DEBUG # for parameters
    helper: DEBUG
  file:
    name: ${LOGFILE_NAME:./${spring.application.name}_log.txt}