CREATE TABLE IF NOT EXISTS content(id SERIAL PRIMARY KEY, uri VARCHAR(255) NOT NULL, title VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL)

CREATE TABLE IF NOT EXISTS location(id SERIAL PRIMARY KEY, url VARCHAR(255) NOT NULL , type VARCHAR(255), content_id VARCHAR(255))