CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS content(uri VARCHAR(255) NOT NULL UNIQUE, title VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL);

CREATE TABLE IF NOT EXISTS location(id SERIAL PRIMARY KEY, url VARCHAR(255) NOT NULL UNIQUE, type VARCHAR(255) NOT NULL, content_id VARCHAR(255));

CREATE TABLE IF NOT EXISTS origin(id UUID PRIMARY KEY DEFAULT gen_random_uuid() , origin_name VARCHAR(255) NOT NULL UNIQUE);