version: "3.7"

#networks:
#  spring:
#  neo:

services:
  admin:
    image: ${ADMIN_IMAGE}
#    networks:
#      - spring
    ports:
      - "127.0.0.1:8090:8090"

  inwent-service:
    image: ${BACKEND_IMAGE}
#    networks:
#      - spring
#      - neo
    environment:
      ADMIN_URL: "admin:8090"
      POSTGRES_USER: inwent
      POSTGRES_PASSWORD: inwent-pass
      POSTGRES_HOST: inwent-postgres
      POSTGRES_PORT: 5432
      SPRING_BOOT_ADMIN_CLIENT_INSTANCE_SERVICE_URL: "http://inwent-service:8080"
    ports:
      - "127.0.0.1:8080:8080"

  inwent-postgres:
    image: postgres:15.1
    environment:
      POSTGRES_USER: inwent
      POSTGRES_PASSWORD: inwent-pass
    ports:
      - "127.0.0.1:5432:5432"

  inwent-postgres-ui:
    image: dpage/pgadmin4
    ports:
      - "127.0.0.1:8091:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@inwent
      PGADMIN_DEFAULT_PASSWORD: pass